### ISSUE TITLE
needs nofn.map!

### ISSUE THREAD

**Issue by jtenner** [finom/babel-plugin-nofn#1]
I have no idea how to implement this because I'm unfamiliar with the provided syntax of the plugin.  I would be happy to help implement it and submit a pull request if you have a bit of time to help me understand how it works.

Thanks,
-Josh

**Comment by finom** [comment]
Didn't know that somebody uses the plugin except me :)

Unfortunately I have no time to implement it :(

**Comment by jtenner** [comment]
> I would be happy to help implement it and submit a pull request if you have a bit of time to help me understand how it works.

I have great use for this because I like using maps in canvas applications.  Any chance you message me and talk about it?

Thanks,
-Josh

**Comment by jtenner** [comment]
It appears nofn.map needs to be aware of the AssignmentExpression parent ![image](https://cloud.githubusercontent.com/assets/3761339/21532136/55a5d126-cd1b-11e6-9238-927033ebb6f5.png)

This is golden. I'm hitting a bug where the actually completely matches the expected :(.

Any help?

**Comment by jtenner** [comment]
Oh it looks like I had a problem here:

```javascript
const build = template(`
	for(
		let TARGET = ARR,
			INDEX = 0,
			VALUE,
			L = TARGET.length,
			RESULT = [];
		(
			VALUE = TARGET[INDEX]
		),
		INDEX < L;
		INDEX++
	) RESULT.push(BODY);
`);
```
I added a single line below the bottom and that broke it:
`ASSIGNEE = RESULT`

Anyway, it seems to be fixed now. I'll submit a pull request later after I build some tests :)

**Comment by jtenner** [comment]
![image](https://cloud.githubusercontent.com/assets/3761339/21532629/f35db8d0-cd1f-11e6-9139-f34f11abdb50.png)

The perf function isn't perfing nofn.map lol. Why is that?

**Comment by jtenner** [comment]
I've been VERY verbose, but I think I'm going to leave it here, if you think you can actually help.

![image](https://cloud.githubusercontent.com/assets/3761339/21532708/c788651a-cd20-11e6-8d80-97f2baa20c68.png)

![image](https://cloud.githubusercontent.com/assets/3761339/21532715/dc7872bc-cd20-11e6-97d2-fcf49f1f1f9b.png)

![image](https://cloud.githubusercontent.com/assets/3761339/21532722/ea9abc7e-cd20-11e6-94dd-cf562060c7e4.png)

It appears my perf tests aren't really all that correct, or I'm not properly configured.  I'm not sure what I need to do, but I've pushed all my changes to my forked [jtenner/babel-plugin-nofn](https://github.com/jtenner/babel-plugin-nofn) repo for you to inspect.

Thank you for your time!

-Josh

**Comment by jtenner** [comment]
NVM. GOT IT.

```javascript
const build = template(`
	for(
		let TARGET = ARR,
			INDEX = 0,
			VALUE,
			L = TARGET.length,
			RESULT = [],
			FUNC = FUNCEXP;
		(
			VALUE = TARGET[INDEX]
		),
		INDEX < L;
		INDEX++
	) {
		RESULT.push(FUNC(VALUE, INDEX));
	}
`);
```

I finally understand it now.

I'm boasting some decent speed too!

![image](https://cloud.githubusercontent.com/assets/3761339/21532926/728e5b84-cd23-11e6-9ad8-2da8212a19bd.png)


I've submitted a pull request for the changes since everything seems to be working.

**Comment by jtenner** [comment]
Hey, is this still a thing? I really liked this babel transform

**Comment by finom** [comment]
Hey. It works fine at one of my projects with latest Babel so far.

**Comment by finom** [comment]
Sorry for long response. I will need to publish it at NPM when I
get to my computer. Thank you.

**Comment by jtenner** [comment]
I may want to revise this pull request. Not sure the speed is good enough actually. This is from such a long time ago haha.

**Comment by jtenner** [comment]
```
map
  _.map: 726.869ms
  Array.prototype.map: 630.814ms
  fast.map: 625.812ms
  nofnLib.map: 641.323ms
  nofn.map: 611.198ms
```
Well I'll be damned. We are faster than `fast.map`. 😮 

Time to celebrate.
